### PR TITLE
Set add action data as xml encoded string

### PR DESCRIPTION
**Pull request by HugoSantiagoBecerraAdan**
- Method executeQuery returns null when declared as non nullable
- Xml encoded data on add or edit methods instead of SimpleXMLElement
- Removal of trailing spaces

### CODE REVIEW

**Review by Jupi007 — CHANGES_REQUESTED** [review]
Hi @HugoSantiagoBecerraAdan,
thanks very very much for your PR ❤️
Your code seems okay for me :)

I just would like you to update the test suite to fit your new change.

Also I just added a CI action #11 in the `master` branch.
Can you rebase your fork so I can run the test suite?

Thanks :)

**Comment by HugoSantiagoBecerraAdan** [comment]
@Jupi007 rebase done, as you requested

**Review by Jupi007 — CHANGES_REQUESTED** [review]
I run the test suite and it fails because it expects to have a `SimpleXMLElement` object in the response, so can you fix that?
Also, can you add a test to expect an exception when `queryAction` is null?

Thanks @HugoSantiagoBecerraAdan  :)

**Comment by HugoSantiagoBecerraAdan** [comment]
@Jupi007 sorry, didn't check the tests, my fault...
Fixed in the last commit.

**Review by Jupi007 — APPROVED** [review]
No problem :)
The code looks good and the test suit pass, so let's merge!

Thanks a lot for your contribution ❤️

**Pull request merged**
